# Generated by Django 2.1.7 on 2020-09-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200927_1511'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Corrunent',
            new_name='Comment',
        ),
    ]
